### ISSUE TITLE
How to Import this Project to Android Studio?

### ISSUE THREAD

**Issue by Mehedi-007** [johnshumon/coursera-android-002-lab-solutions#1]
How can I successfully import this project to my Android Studio and Build and Run it successfully?

Here are my Android Studio details:

My Android Studio version: 3.1.2 Build #AI-173.4720617, built on April 14, 2018 JRE: 1.8.0_152-release-1024-b01 x86_64 JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o Mac OS X 10.12.3 Gradle version: 4.4.1 Android Plugin version: 3.1.2

Thanks in advance!

**Comment by johnshumon** [comment]
Well you can clone this repo. When done, load each of exercise as a individual project in your android studio.

**Comment by Mehedi-007** [comment]
Yes, I did exactly the same. But there arising many issues while building a
project. Could you please show me the exact procedures to import say the
ActivityTest project to Android Studio(v 3.1.2 Gradle v4.4) and
successfully build and run the project? Which files I've to delete and
which files should I've to import, etc. Or any other changes. Please let me
know. Thanks in advance!

**Comment by johnshumon** [comment]
To be honest I don't know exactly. as you can see the repo is four years old and there's been many updates in android studio. I haven't done any android development in ages. What issues/errors do exactly does studio rises?

**Comment by Mehedi-007** [comment]
I've tried in different ways. And each time it comes up with different
types of errors. Mostly compatibility issues and path not find errors.

**Comment by johnshumon** [comment]
I would reckon googling exact problem/error would help you in this case.

**Comment by Mehedi-007** [comment]
Thank you! I fixed the problem.
